{
    "name": "Hospital CRM",
    "version": "1.0",
    "author": "Halyna Petrova",
    "category": "Human Resources",
    "depends": [],
    "data": [
        'security/ir.model.access.csv',
        'views/menu_items.xml',
        'views/patient.xml',
        'views/doctor.xml',
        'views/analysis.xml',
        'views/diagnosis.xml',
        'views/disease_type.xml',
        'views/disease_catalog.xml',
        'views/research_type.xml',
        'views/research_catalog.xml',
        'views/doctor_visit.xml',
        'views/doctor_history.xml',
        'views/doctor_schedule.xml',
    ],
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
